#!/usr/bin/env python
#
# $Id: fitgui_dev,v 1.1 2005/01/06 18:45:12 jsy1001 Exp $

"""Run fitgui using specified clfit.

Usage: fitgui_dev [path_to_clfit]

path_to_clfit defaults to './clfit'

"""
 
import fitgui
import sys

if __name__ == '__main__':

    if len(sys.argv) == 1:
        exe = './clfit'
    elif len(sys.argv) == 2 and sys.argv[1] != '-h' and sys.argv[1] != '--help':
        exe = sys.argv[1]
        del sys.argv[1]
    else:
        print __doc__
        sys.exit(2)

    fitgui._main(altExe=exe)
 
# Local Variables:
# mode: python
# End:
